coder/coder-jetbrains-toolbox

src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/models/WorkspaceAndAgentStatus.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/sdk/v2/models/CreateWorkspaceBuildRequest.kt

- facade for Coder's  REST endpoint to remove a workspace
- pop-up dailog for user to confirm the workspace removal
- add support for status icons and as a bonus Toolbox is now displaying nice animation around the header bar when workspace is starting or stopping
- resolves #7 
Small note: info and error dialogs created with ToolboxUi#showInfoPopup, ToolboxUi#showYesNoPopup, and ToolboxUi#showOkCancelPopup only appear on the main page where all environments are listed.  JetBrains is addressing the issue but until then user can interact with the confirmation dialog only from the front page.

Support for removing workspaces

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/release.yml
.gitignore
CHANGELOG.md
build.gradle.kts
gradle.properties
gradle/libs.versions.toml

- support Changelog files and automatic update after a release
- workflows to build and publish release drafts
- support for automatic dependencies update via Github's dependabot.

Implement CI pipeline

---

src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt

- the action buttons like (start/stop/update) did not change visibility or enabled property when the workspace changed its running status
- this fix regenerates the list of available actions in order to force a re-draw in UI when workspace status changes
- resolves #12

fix: env. action buttons state

---

src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt

The auto connect happens only when:
- workspace is running
- the user clicks on one of the environments in the main page
- there isn't already an established connection

impl: auto-connect to toolbox backend

---

.github/workflows/build.yml

- gh cli (gh release create) does not need \n and \r to be encoded as it should correctly interpret raw newlines from files.
- also  make zip available to download from draft release as it is easier to find

fix: release notes formatting

---

.github/workflows/build.yml

- and also fix the zip and release notes publish
- there is no need to unzip and then later re-zip files to be published as draft because Kotlin does the zip in the first place, we just need to upload it and download it in the jobs that need it.
- similar, release note files have to be shared between jobs by upload&download

refactor: simplify build and draft release jobs

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/views/CoderPage.kt
src/main/resources/localization/defaultMessages.po

- LAF support in Toolbox is quite primitive, it turns out icon support for light and dark themes is enabled by a masked flag on the icons.
- the mask flag controls whether the svg colors are inverted in light&dark themes.
Among other things we also fixed and issue with the `Start` button which remained active when a workspace was stopped and outdated. In order to be more consistent with the web client we renamed the button to `Update and start` to reflect that it also starts the workspace.
Running and outdated workspaces also received a new action button: `Update and restart`.
- resolves #31

Impl: icons with support for light&dark themes

---

build.gradle.kts

- marketplace token should be in JETBRAINS_MARKETPLACE_PUBLISH_TOKEN env. variable
- calls the proper api for upload based on whether it's the first release version or not

impl: improve publish task

---

.github/workflows/release.yml

- initial publish was done manually
- but we still want a gh release so we have to augment the release workflow to build the zip file because the publish task does not run

build: update publish workflow

---

build.gradle.kts

We need to use the correct vendor ID: https://plugins.jetbrains.com/vendor/coder

fix: use correct vendor id

---

src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/CoderToolboxExtension.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt
src/main/kotlin/com/coder/toolbox/views/ConnectPage.kt

Context:
- okhttp uses an HTTP/2 connection to the coder rest api in order to resolves the workspaces.
- HTTP/2 uses a single TCP connection for multiple requests (multiplexing). If the connection is idle, the http server can close that connection, with client side ending in a socket timeout if it doesn't detect the drop in time.
- similarly on the client side, if the OS goes into sleep mode, the connection might have been interrupted. HTTP/2 doesn't always detect this quickly, leading to stale streams when Toolbox wakes up.
Implementation:
- we could try to force the client to use HTTP/1 which creates a TCP connection for each request, but from my testing it seems that configuring a retry strategy when a client attempts to reuse a TCP connection that has unexpectedly closed  plus …

fix: socket connection timeout

---

.github/workflows/release.yml
CHANGELOG.md
gradle.properties

- manual update the changelog (release pipeline failed because it needs some adjustments around artifact upload)
- increase version to 0.2.0
- update release workflow to force upload of the release artifact. Draft release already creates and attaches the artifact but we want to upload the exact same thing as what was published to the jetbrains marketplace.

Update after manual release

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

- previously, ssh reconfiguration was triggered only when new workspaces were added, and
the ssh config was generated only with the additional environments removing the configuration
for the previous ones. This means that when a new workspace is created from the web dashboard,
the old workspaces are no longer accessible via ssh from Toolbox
- now, the logic ensures ssh reconfiguration happens whenever the set of environments changes
(including additions or removals), making it more robust, and configuration happens for all
valid workspaces.
- resolves #14

fix: improve ssh config logic when workspaces change

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/resources/localization/defaultMessages.po

- right now there are two confirmation dialogs when removing a workspace from Toolbox
- with this patch we force Toolbox to discard its default dialog and show a custom one with
the Coder titles and messages.
- resolves #60

fix: override default delete confirmation dialog

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

- up until now after users hits the drop-down log out action he was presented with a blank page and had to restart Toolbox in order to reach out to the login screen.
- resolves #34

fix: redirect user to the login screen after log out from a deployment

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt

- right now ssh automatically connects to the workspace when a user selects it from the main env. page. However, if the user manually disconnects from the hamburger menu, the SSH is no longer automatically established afterward.
- the reason for this behavior was that the connection request flag that triggered the ssh connection behind the scenes was never reset. In order to reset we have to know when a user hits the disconnect button.
- fortunately Toolbox provides two callbacks, one before establishing the ssh connection and another one right after disconnect. Even though we don't know the reason for disconnect it's still a good opportunity to reset the request flag.
- resolves #38

fix: ssh connection to a workspace is established only once

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/views/AuthWizardPage.kt
src/main/kotlin/com/coder/toolbox/views/ConnectStep.kt

- happens when an error is encountered during connection (like exceptions caused by an expired token)
- right now the auth wizard stays on the last step.
- with this changeset the auth steps reset to the initial sign in for auto-connect, or it goes back one step back to the token input step for manual authentication

fix: go to previous step when connection fails

---

CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt
src/main/kotlin/com/coder/toolbox/util/LinkMap.kt
src/test/kotlin/com/coder/toolbox/util/LinkHandlerTest.kt

The following topics are covered:
- documentation on how to install the plugin
- URI handling documentation
- release procedure
- resolves #64
This PR also includes:
- improved Error Reporting for Unresolved Agents, now  it shows a clear, human-readable error message instead
- a rename of `project_path` query param to `folder`
- and a fix to no longer ask for coder deployment details when user wants to install the plugin via URI.
P.S: Some of the topics were copied without shame from the old Coder Gateway plugin.

doc: initial guide to the plugin

---

src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

fix: show loading indicator instead of "No workspaces yet" (#44)

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/sdk/ex/APIResponseException.kt
src/main/kotlin/com/coder/toolbox/sdk/v2/models/ApiErrorResponse.kt
src/main/kotlin/com/coder/toolbox/views/CoderPage.kt

- in fact we will now jump to the login screen for any error other than socket timeout because of an OS wake-up
- this patch also contains a re-work of the REST API exception. Coder backend sends very detailed messages with the reason for the http calls to be rejected. We now un-marshall those responses and fill the exception system with better details.

fix: show login screen when token expires during workspace polling

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

- detect if there is an os wake-up for all types of errors
- if there is an os wake-up we try to re-init the http client.
- if that doesn't work out, the polling stops and redirects to the autologin screen.
- the autologin screen will display an error and stop the authentication if errors are encountered.

fix: simplify and improve error handling during workspace polling

---

CHANGELOG.md
README.md
gradle.properties
src/main/kotlin/com/coder/toolbox/CoderToolboxContext.kt
src/main/kotlin/com/coder/toolbox/CoderToolboxExtension.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt
src/main/kotlin/com/coder/toolbox/views/ConnectStep.kt
src/test/kotlin/com/coder/toolbox/cli/CoderCLIManagerTest.kt
src/test/kotlin/com/coder/toolbox/sdk/CoderRestClientTest.kt

- proxy credentials are not yet supported as they were not exposed in Toolbox settings
- system and manual proxy configuration supported.
- manual tests included system wide settings and manual http settings.
- resolves #39

impl: support for using proxies to access Coder REST API

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/models/WorkspaceAndAgentStatus.kt
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt

- if workspace or agent start with error, we report the workspace as started with errors and highlight the text with red.
- the workspace is still marked as reachable even though it is unhealthy but we no longer connect automatically to the workspace via ssh when user selects the workspace from the env list.

fix: agent error reporting and handling

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/cli/CoderCLIManager.kt
src/test/resources/fixtures/outputs/append-blank-newlines.conf
src/test/resources/fixtures/outputs/append-blank.conf
src/test/resources/fixtures/outputs/append-no-blocks.conf
src/test/resources/fixtures/outputs/append-no-newline.conf
src/test/resources/fixtures/outputs/append-no-related-blocks.conf
src/test/resources/fixtures/outputs/disable-autostart.conf
src/test/resources/fixtures/outputs/extra-config.conf
src/test/resources/fixtures/outputs/header-command-windows.conf
src/test/resources/fixtures/outputs/header-command.conf
src/test/resources/fixtures/outputs/log-dir.conf
src/test/resources/fixtures/outputs/multiple-agents.conf
src/test/resources/fixtures/outputs/multiple-users.conf
src/test/resources/fixtures/outputs/multiple-workspaces.conf
src/test/resources/fixtures/outputs/no-disable-autostart.conf
src/test/resources/fixtures/outputs/no-report-usage.conf
src/test/resources/fixtures/outputs/replace-end-no-newline.conf
src/test/resources/fixtures/outputs/replace-end.conf
src/test/resources/fixtures/outputs/replace-middle-ignore-unrelated.conf
src/test/resources/fixtures/outputs/replace-middle.conf
src/test/resources/fixtures/outputs/replace-only.conf
src/test/resources/fixtures/outputs/replace-start.conf
src/test/resources/fixtures/outputs/url.conf
src/test/resources/fixtures/outputs/wildcard.conf

From my testing, Toolbox forwards through SSH (i.e. through Coder) a remote port associated with the IDE
running in server mode, to localhost in order for the server (i.e. the remote IDE) to communicate with
JBClient. Unlike with Gateway, Toolbox manages to reuse the SSH connection, and it doesn't open a separate
one for port forwarding.
From Gateway we inherited two ssh hostnames per each workspace, one for background connections that did not
involve running IDEs. Coder discards the bg. connection from the collected metrics in order to
avoid double counting. Since Toolbox manages to re-use the connection we don't need to worry
about double counting.
For this particular change, I deployed the latest Coder version with prometheus metrics and experiments
enabled (i.e. --prometheus-enable …

chore: remove ssh background config

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

There is a brief moment between manual authentication and workspace poller initialization and execution where we see a "No workspaces yet" which is misleading. Instead, a loading indicator/message  should be displayed.
- resolves #103

fix: misleading "No workspaces yet" during manual authentication

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt

when the workspace is stopped. This action will be available only when the workspace is up and running (even when it is running with errors)

fix: open web terminal action is no longer displayed

---

README.md

This PR documents a number of things:
- how to configure the debug level before reporting any Coder plugin issue
- how to collect or view the Toolbox log files. 
- the settings page and the available options

doc: improve documentation and debugging steps

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/models/WorkspaceAndAgentStatus.kt

There were a couple of discrepancies in the status reporting especially around icons and colors:
- offline workspaces are marked by a new "offline" icon and a gray color (instead of a half pie icon with a red color)
- stopping state now has a gray progress spinner
- same for deleting state which previously used the offline icon instead of the spinner.
- failed workspaces used to render a gray offline icon instead of a red warning (exclamation mark) sign.
- there was no progress while establishing the SSH connection. Now we have a "SSHing" label with a circular progress bar while connecting to the SSH.

impl: workspace status reporting (color and icons)

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt

Similarly to the web dashboard, `Stop` should be available alongside `Update and restart` action when a workspace is running but with a template out of date.

fix: Stop action should be available when workspace is out of date

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt

This PR fixes an issue with URI handling which was not installing the exact same version requested by the user if the version was available for install on the workspace.

fix: install the build number if available

---

src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/sdk/v2/models/CreateWorkspaceBuildRequest.kt
src/main/kotlin/com/coder/toolbox/sdk/v2/models/WorkspaceBuildReason.kt

This PR is part of https://github.com/coder/coder/pull/18827 which introduces new build reason values to identify what type of connection triggered a workspace build, helping to troubleshoot workspace-related issues.

feat: set 'jetbrains_connection' as build reason on workspace start

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/cli/downloader/CoderDownloadService.kt
src/test/kotlin/com/coder/toolbox/cli/CoderCLIManagerTest.kt

Add validation for CLI downloads that ensures the Content-Type header is indicating a binary stream (`application/octet-stream`), including common variants with parameters. This prevents saving unexpected HTML or other non-binary responses (e.g., from frontend dev servers on :8080) as binaries, improving reliability and providing clearer error feedback.

fix: enforce Content-Type to accept only binary responses

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt

Some users complained that Coder Toolbox has a noticeable delay in rendering the workspaces
status compared with the web Dashboard, even though they have the same polling frequency,
which is every 5 seconds.
However, the web Dashboard also reacts and when the tab receives focus from the user which
improves the experience. This PR tries to implement the same behavior, when Coder Toolbox
screen becomes visible the polling is triggered immediately which should result in a status update.

impl: poll workspaces when Toolbox screen becomes visible

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/cli/CoderCLIManager.kt
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt
src/main/kotlin/com/coder/toolbox/views/CoderCliSetupWizardPage.kt
src/main/kotlin/com/coder/toolbox/views/CoderSettingsPage.kt
src/main/kotlin/com/coder/toolbox/views/ConnectStep.kt

- this commit add descriptive names to launched coroutines for better stack traces.
- extra logging lines during connection setup. Should be helpful in cases where the coroutines
fail with exceptions

impl: improved debugging with named coroutines and additional logging

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/views/CoderCliSetupWizardPage.kt
src/main/kotlin/com/coder/toolbox/views/ConnectStep.kt
src/main/kotlin/com/coder/toolbox/views/DeploymentUrlStep.kt
src/main/kotlin/com/coder/toolbox/views/ErrorReporter.kt

The try/catch block raised NPE in the `notify` if another exception was raised after the context containing the URL was reset - so that means an error in the onConnect handler. In addition, some of the reset steps were moved after onConnect to make sure they execute only if onConnect callback is successful.
Because of the fault in how the steps were arranged, the original exception was never logged instead a misleading NPE was treated by the coroutine's exception handler.

fix: NPE during error reporting

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/cli/downloader/CoderDownloadService.kt

This PR fixes download failure for Windows .exe binaries by relaxing strict Content-Type checks. Previously, the plugin only accepted application/octet-stream, causing failures when .exe files were served as application/x-msdos-executable by some servers.
- resolves #187

fix: relaxed Content-Type checks for CLI download

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/CoderRemoteEnvironment.kt
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/views/CoderCliSetupWizardPage.kt
src/main/kotlin/com/coder/toolbox/views/CoderPage.kt
src/main/kotlin/com/coder/toolbox/views/CoderSettingsPage.kt

JetBrains team reported in the past a couple of errors in the log, one of them being `A workspace build is already active`. The issue can be reproduced if the user hits the `Stop` action for example quite quick. It takes maybe one or two seconds to make rest api request, then for the backend to enqueue the build and change the workspace action. If we hit the action buttons really fast then this error could be reproduced.
One approach I tried was to disable the action buttons in the context menu for the duration the request is executed. But for some reason the "enabled" property is not working in context menu, only when the actions are rendered on a UI "page".
Instead, I decided to refactor the existing code and (also) visually report the errors in the UI screen to make the user aware in …

fix: report errors while running actions

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/util/TLS.kt
src/test/kotlin/com/coder/toolbox/util/AlternateNameSSLSocketFactoryTest.kt
src/test/kotlin/com/coder/toolbox/util/CoderHostnameVerifierTest.kt

When establishing TLS connections, SNI resolution may fail if the configured altHostname contains `_` or any other characters not allowed by domain name standards (i.e. letters, digits and hyphens).
This change introduces a relaxed SNI resolution strategy which ignores the LDH rules completely. Because this change goes hand in hand with auth. via certificates, I was able to reproduce the issue only via UTs. At this point the official Coder releases supports only auth. via API keys.

fix: relaxed SNI hostname resolution

---

src/main/kotlin/com/coder/toolbox/util/TLS.kt

This PR documents why the SNI is altered during TLS handshake and why a certificate SAN is compared against an alternate hostname.

doc: the augmentation around SNI & certificate validation

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/coder/toolbox/CoderRemoteProvider.kt
src/main/kotlin/com/coder/toolbox/CoderToolboxContext.kt
src/main/kotlin/com/coder/toolbox/settings/ReadOnlyCoderSettings.kt
src/main/kotlin/com/coder/toolbox/store/CoderSecretsStore.kt
src/main/kotlin/com/coder/toolbox/store/CoderSettingsStore.kt
src/main/kotlin/com/coder/toolbox/store/StoreKeys.kt
src/main/kotlin/com/coder/toolbox/views/DeploymentUrlStep.kt

Context: Toolbox can store key/value pairs in two places:
- a settings store which is backed by a clear text json file per each plugin
- native keystore for sensitive data
At the same time some of Coder's clients (ex: Netflix) would like to deploy at scale preconfigured settings for Toolbox. Most of the needed settings are part of json backed store except the last used URL.
This PR reworks the code around the last used URL/token and moves the URL in the json backed store, making it easy to configure. At the same time we still support the pair stored in the native keystore for backward compatibility reasons.

impl: store last used URL in Toolbox Settings Store

---

src/test/kotlin/com/coder/toolbox/util/CoderProtocolHandlerTest.kt

Inspired by https://github.com/coder/jetbrains-coder/pull/585/commits/5f0e3633d7da533a24ef25172b5a664a5bdd169b which took a while to debug and understand. This rewrite arguably provides better test names, better data setup with cleaner descriptions.

test: rewrite UTs related to agent resolution in URI handling

---

CHANGELOG.md
src/main/kotlin/com/coder/toolbox/cli/CoderCLIManager.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderHttpClientBuilder.kt
src/main/kotlin/com/coder/toolbox/sdk/CoderRestClient.kt
src/main/kotlin/com/coder/toolbox/util/CoderProtocolHandler.kt
src/main/kotlin/com/coder/toolbox/views/ConnectStep.kt

Replace !! operators with safe idiom takeIf/let chains. The non-null assertions were unsafe in concurrent scenarios where one thread could potentially modify the settings while another thread reads and makes non-null assertions.

refactor: remove unsafe non-null assertions to prevent race condition
